### ISSUE TITLE
Error with firewall_ids (python code)

### ISSUE THREAD

**Issue by pea-io** [pulumi/pulumi-hcloud#127]
### What happened?

Hello,

I'm trying to reproduce the example provided in Python here: https://www.pulumi.com/registry/packages/hcloud/api-docs/firewall/
But when i run `pulumi up`, i have this error:

```
Diagnostics:
  hcloud:index:Server (jarkartanet0):
    error: hcloud:index/server:Server resource 'jarkartanet0' has a problem: Attribute must be a whole number, got 374907. Examine values at 'Server.FirewallIds'.
```

The firewall id is the good one (374907) but it doesn't work.
If i replace:
```
firewall_ids=[myfirewall.id]
```
by
```
firewall_ids=[374907]
```

it works.

### Steps to reproduce

Follow the example provided here (Python): https://www.pulumi.com/registry/packages/hcloud/api-docs/firewall/

### Expected Behavior

`pulumi up` should work

### Actual Behavior

pulumi ends with an error:
```
Diagnostics:
  hcloud:index:Server (jarkartanet0):
    error: hcloud:index/server:Server resource 'jarkartanet0' has a problem: Attribute must be a whole number, got 374907. Examine values at 'Server.FirewallIds'.
```

### Versions used

```
CLI          
Version      3.30.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
hcloud  1.8.0
python  unknown

Host     
OS       debian
Version  11.3
Arch     x86_64

This project is written in python (/home/pea/xxxxx/venv/bin/python3 v3.10.4)

Current Stack: tezos

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:tezos::iac::pulumi:pulumi:Stack::iac-tezos
pulumi:providers:hcloud         urn:pulumi:tezos::iac::pulumi:providers:hcloud::default_1_8_0
hcloud:index/server:Server      urn:pulumi:tezos::iac::hcloud:index/server:Server::jarkartanet0
hcloud:index/firewall:Firewall  urn:pulumi:tezos::iac::hcloud:index/firewall:Firewall::tezos-fw


Found no pending operations associated with tezos

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pea
User           pea
Organizations  pea

NAME           VERSION
pip            22.0.4
pulumi-hcloud  1.8.0
setuptools     62.1.0
wheel          0.37.1

Pulumi locates its logs in /tmp by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @pea-io - I believe this is a manifestation of [a bug in the pulumi-terraform bridge](https://github.com/pulumi/pulumi-terraform-bridge/issues/352) which is reading out a string when it should be an integer. While we work on a permanent fix, we recommend using [Pulumi Apply](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply) to re-cast that ID.
