### ISSUE TITLE
Changing PublicKey arg does not result in replacement

### ISSUE THREAD

**Issue by daenney** [pulumi/pulumi-hcloud#157]
### What happened?

I'm provisioning 2 SSH keys. Whenever I change the `name` passed into `hcloud.NewSshKey()` the resource drift is detected and it wants to create a new key and delete the old one.

However, when I update the public key passed in `hcloud.SshArgs{}` no resource drift is detected and the key does not get updated.

### Steps to reproduce

In `Pulumi.prod.yaml`:

```yaml
config:
  pulumi:disable-default-providers: ["*"]
  infra:ssh_keys:
  - name: laptop
    key: ssh-ed25519 ... daenney@laptop
  - name: desktop
    key: ssh-ed25519 ... daenney@desktop
```

The project itself, `main.go`:

```go
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		prov, err := hcloud.NewProvider(ctx, "provider", &hcloud.ProviderArgs{
			Token: config.New(ctx, "hcloud").RequireSecret("token"),
		})
		if err != nil {
			return err
		}

		cfg := config.New(ctx, "infra")

		if err := internal.EnsureKeypairs(ctx, prov, cfg); err != nil {
			return err
		}
		return nil
	})
}
```

And the SSH code, `internal/ssh.go`:

```go
type Keypair struct {
	Name string
	Key  string
}

func EnsureKeypairs(ctx *pulumi.Context, prov *hcloud.Provider, cfg *config.Config) error {
	var kps []Keypair
	if err := cfg.GetObject("ssh_keys", &kps); err != nil {
		return err
	}

	for _, key := range kps {
		fmt.Printf("%+v\n", key)
		if _, err := hcloud.NewSshKey(
			ctx,
			key.Name,
			&hcloud.SshKeyArgs{PublicKey: pulumi.String(key.Key)},
			pulumi.Provider(prov),
		); err != nil {
			return err
		}
	}
	return nil
}
```

### Expected Behavior

According to the docs on https://www.pulumi.com/registry/packages/hcloud/api-docs/sshkey/, changing the `publicKey` should result in resource replacement.

### Actual Behavior

When I change the `key` field in the YAML of any of the 2 keys, `pulumi up` results in no changes. The `fmt.Printf()` however results in the expected (changed) value for the key being printed.

### Output of `pulumi about`

CLI          
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME    VERSION
go      unknown
hcloud  1.10.1

Host     
OS       arch
Version  
Arch     x86_64

This project is written in go: executable='/usr/bin/go' version='go version go1.19.4 linux/amd64'

Current Stack: prod

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:prod::infra::pulumi:pulumi:Stack::infra-prod
pulumi:providers:hcloud         urn:pulumi:prod::infra::pulumi:providers:hcloud::provider
hcloud:index/firewall:Firewall  urn:pulumi:prod::infra::hcloud:index/firewall:Firewall::firewall
hcloud:index/sshKey:SshKey      urn:pulumi:prod::infra::hcloud:index/sshKey:SshKey::desktop
hcloud:index/sshKey:SshKey      urn:pulumi:prod::infra::hcloud:index/sshKey:SshKey::laptop

Found no pending operations associated with prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/daenney
User           daenney
Organizations  daenney

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-hcloud/sdk  1.10.1
github.com/pulumi/pulumi/sdk/v3      3.44.2

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by daenney** [comment]
It looks like I'm partially mistaken. The key will change if the key (the string of random letters/numbers) itself changes. But I can change the key type `ssh-ed25519` to `ssh-rsa` without it changing and the same goes to the comment.

I'm not sure if this is an issue with Pulumi or the underlying provider.

**Comment by mikhailshilkov** [comment]
@daenney It looks like there is a custom diff calculation function that compares only fingerprints: https://github.com/hetznercloud/terraform-provider-hcloud/blob/18a0ccae91b92f2d5bd91ec2e7060d99e875468d/internal/sshkey/resource.go#L62-L70

I'm not super familiar with this resource, but it sounds like this behavior is by design. Let me know if you disagree.
