### ISSUE TITLE
when providing server.image as id, server gets replaced every time

### ISSUE THREAD

**Issue by rafalkrupinski** [pulumi/pulumi-hcloud#174]
### What happened?

I want to pin down the image version using image id instead of name.
```typescript
new hcloud.Server("bastion", {
    image: "45557056",,
    serverType: "cx11",
    sshKeys: sshKeys,
    location: "nbg1",
});
```
`pulumi up` always wants to replace the server, and the details shows:
```
    +-hcloud:index/server:Server: (replace)
        [id=29787771]
        [urn=urn:pulumi:dev::infra::hcloud:index/server:Server::worker1]
        [provider=urn:pulumi:dev::infra::pulumi:providers:hcloud::default_1_10_2::2d09c0f9-d868-4227-89a9-02b88ac073de]
      ~ image   : "debian-11" => "45557056"
 ```

### Expected Behavior

Pulumi should recognise that the server didn't change and leave it alone.

### Steps to reproduce

1. get list of images
    `hcloud image list`
2. create pulumi script with a server using image id, e.g.
    `new hcloud.Server("bastion", {
    image: "45557056",,
    serverType: "cx11",
    sshKeys: sshKeys,
    location: "nbg1",
});
`
3. run `pulumi up`
4. run `pulumi up`

### Output of `pulumi about`

CLI          
Version      3.56.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.50.0
hcloud  1.10.2
nodejs  unknown
random  4.11.3

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.19.1'

Current Stack: dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::infra::pulumi:pulumi:Stack::infra-dev
pulumi:providers:hcloud                     urn:pulumi:dev::infra::pulumi:providers:hcloud::default_1_10_2
pulumi:providers:random                     urn:pulumi:dev::infra::pulumi:providers:random::default_4_11_3
hcloud:index/network:Network                urn:pulumi:dev::infra::hcloud:index/network:Network::network
hcloud:index/sshKey:SshKey                  urn:pulumi:dev::infra::hcloud:index/sshKey:SshKey::admin-ssh
random:index/randomPassword:RandomPassword  urn:pulumi:dev::infra::random:index/randomPassword:RandomPassword::k3s-token
hcloud:index/networkSubnet:NetworkSubnet    urn:pulumi:dev::infra::hcloud:index/networkSubnet:NetworkSubnet::network-subnet
hcloud:index/server:Server                  urn:pulumi:dev::infra::hcloud:index/server:Server::bastion
hcloud:index/server:Server                  urn:pulumi:dev::infra::hcloud:index/server:Server::control
hcloud:index/serverNetwork:ServerNetwork    urn:pulumi:dev::infra::hcloud:index/serverNetwork:ServerNetwork::control-server-subnet
hcloud:index/server:Server                  urn:pulumi:dev::infra::hcloud:index/server:Server::worker1
hcloud:index/serverNetwork:ServerNetwork    urn:pulumi:dev::infra::hcloud:index/serverNetwork:ServerNetwork::worker-subnet

Found no pending operations associated with dev

Backend        
Name           vanadium
URL            gs://infra-4747072
User           matte
Organizations  

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /home/matte/Documents/Projects/infra3/pulumi/yarn.lock or /home/matte/Documents/Projects/infra3/pulumi/package-lock.json
m

$ pnpm list
Legend: production dependency, optional only, dev only

infra /home/matte/Documents/Projects/infra3/pulumi

dependencies:
@pulumi/gcp 6.50.0
@pulumi/hcloud 1.10.2
@pulumi/pulumi 3.56.0
@pulumi/random 4.11.3

devDependencies:
@types/node 16.18.14

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @rafalkrupinski. This looks a lot like https://github.com/pulumi/pulumi-hcloud/issues/170. Can you try with hcloud [v1.10.3](https://github.com/pulumi/pulumi-hcloud/releases/tag/v1.10.3). It might fix your issue.

**Comment by rafalkrupinski** [comment]
It is kinda similar, but the problem persists on 1.10.3.

BTW, is 1.10.3 compatible with 1.10.2?
I'm getting these on pulumi up:
`error: diffing urn:pulumi:...-subnet: value is not known`

luckily I was able to simply remove the subnets.

**Comment by iwahbe** [comment]
Thanks for checking. I'll take a deeper look soon. 1.10.3 should be compatible with 1.10.2. It might be an issue with the new diff logic. CC @t0yv0

**Comment by rafalkrupinski** [comment]
So just to make it clear, I had a ServerNetwork with serverid and subnetId created with hcloud 1.10.2, and after upgrading to 1.10.3 it couldn't do diff on `pulumi up`. Let me know if you need an example code.

**Comment by t0yv0** [comment]
Yes we would need the example code please.

**Comment by t0yv0** [comment]
I can try with an example program from our docs:

```
import * as pulumi from "@pulumi/pulumi";
import * as hcloud from "@pulumi/hcloud";

const node1 = new hcloud.Server("node1", {
    image: "debian-9",
    serverType: "cx11",
});
const mynet = new hcloud.Network("mynet", {ipRange: "10.0.0.0/8"});
const foonet = new hcloud.NetworkSubnet("foonet", {
    networkId: mynet.id,
    type: "cloud",
    networkZone: "eu-central",
    ipRange: "10.0.1.0/24",
});
const srvnetwork = new hcloud.ServerNetwork("srvnetwork", {
    serverId: node1.id,
    networkId: mynet.id,
    ip: "10.0.1.5",
});```

**Comment by t0yv0** [comment]
Here's what I tried.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as hcloud from "@pulumi/hcloud";

function num(strout: pulumi.Output<String>): pulumi.Output<number> {
    return strout.apply(x => {
        console.log("Converting", x, "to", Number(x));
        return Number(x);
    })
}

const node1 = new hcloud.Server("node1", {
    image: "debian-11",
    serverType: "cx11",
});

const mynet = new hcloud.Network("mynet", {ipRange: "10.0.0.0/8"});

const foonet = new hcloud.NetworkSubnet("foonet", {
    networkId: mynet.id.apply(x => {
        console.log("Converting", x, "to", Number(x));
        return Number(x);
    }),
    type: "cloud",
    networkZone: "eu-central",
    ipRange: "10.0.1.0/24",
});

export const foonet_id = foonet.id;

const srvnetwork = new hcloud.ServerNetwork("srvnetwork", {
    serverId: num(node1.id),
    subnetId: foonet.id,
    ip: "10.0.1.5",
});

export const srvnetwork_id = srvnetwork.id;
```

1. install hcloud 1.10.2
2. pulumi up # ok
3. install hcloud 1.10.3
4. pulumi up # zero diff, ok

**Comment by rafalkrupinski** [comment]
IDK, I couldn't reproduce the diff error either.

Anyway, here's the repo for the image ID problem:
https://github.com/oeklo/pulumi-image-id
