### ISSUE TITLE
Importing hcloud:index:Server

### ISSUE THREAD

**Issue by MartinSchmidt123** [pulumi/pulumi-hcloud#33]
When trying to import an existing server resource using
`pulumi import hcloud:index:Server test 1234567` 
the following error is shown
```bash
Previewing import ([..])

View Live: [..]

     Type                    Name                      Plan       Info
     pulumi:pulumi:Stack     [..]                               1 error
 =   └─ hcloud:index:Server  test                    import     1 error
 
Diagnostics:
  pulumi:pulumi:Stack ([..]):
    error: preview failed
 
  hcloud:index:Server (test):
    error: Preview failed: unrecognized resource type (Read): hcloud:index:Server
```
I am using pulumi with python and the following versions:
 * pulumi v2.15.5
 * pulumi-hcloud 0.4.0

I am not sure if this is a feature request or a bug report. 

At least the [underlying terraform provider](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#import) supports importing server resources,
But the [pulumi hcloud documentation](https://www.pulumi.com/docs/reference/pkg/hcloud/server/) does not mention importing.

The [blog post](https://www.pulumi.com/blog/pulumi-import-generate-iac-for-existing-cloud-resources/) mentions the following pulumi provider where importing is also documented: https://www.pulumi.com/docs/reference/pkg/aws/ec2/vpc/#import
Maybe we can learn from this and adjust the hcloud provider to add importing documentation and functionality.

**Comment by leezen** [comment]
Apologies for the documentation missing. I'll keep this open to track that.

In terms of the import itself, the type token should be `hcloud:index/server:Server`. Could you please try again with `pulumi import hcloud:index/server:Server test 1234567` and see if that unblocks you?

**Comment by leezen** [comment]
@stack72 Do you mind checking on the import docs for this provider?

**Comment by MartinSchmidt123** [comment]
Thank you for your help. Using `hcloud:index/server:Server` as type for importing works.
