### ISSUE TITLE
AttributeError for VolumeAttachment volume_id and server_id

### ISSUE THREAD

**Issue by nzagorsky** [pulumi/pulumi-hcloud#46]
Using Python example from the guide: https://www.pulumi.com/docs/reference/pkg/hcloud/volumeattachment/
I'm getting an error for wrong type of the input.

![image](https://user-images.githubusercontent.com/7213838/108916543-77365a00-763f-11eb-9d1a-05d9eea52d18.png)

## Expected behavior
VolumeAttachment should be properly created

## Current behavior
VolumeAttachment is not created due to the AttributeError

## Steps to reproduce

1. Create new stack
2. Copypaste example from the snippet on official documentation website

**Comment by nzagorsky** [comment]
UPD:
`instance_id = instance.id.apply(lambda x: int(x))` 
Type conversion helps here and things work as expected. Either documentation or types needs to be updated.

**Comment by rafalkrupinski** [comment]
Is there more to it than just changing this and similar lines?
https://github.com/pulumi/pulumi-hcloud/blob/e1e2857334f1d021e957e27223575092da3344d0/provider/cmd/pulumi-resource-hcloud/schema.json#L84
