### ISSUE TITLE
Deleting server

### ISSUE THREAD

**Issue by libvirtadept** [pulumi/pulumi-hcloud#56]
## Affected feature

Hi
I didn't found thing that can delete server that we don't need anymore.
Is it implemented or not ?

Thanks :)

**Comment by viveklak** [comment]
Did you try deleting the server reference from your code? pulumi destroy will also delete it (along with the rest of your stack).

**Comment by libvirtadept** [comment]
Nope, didn't tried. But we may need to delete server after sometime (after 1 week for example).
I've thought that we can call func to forcefully delete it.
