### ISSUE TITLE
segfault when I forget CIDR suffix on my source_ips

### ISSUE THREAD

**Issue by bmillwood** [pulumi/pulumi-hcloud#598]
### Describe what happened

See sample program / log output. If I replace the `"::"` in `source_ips` with `"::/0"` everything is fine.

(I don't object to this failing, but my guess is that failing with a segfault is not intended.)

### Sample program

Python template with this `__main__.py`:
```python
import pulumi
import pulumi_hcloud as hcloud

fw = hcloud.Firewall(
    "fw",
    rules=[
        hcloud.FirewallRuleArgs(
            direction="in",
            protocol="tcp",
            description="ssh",
            port="22",
            source_ips=[
                "::",
            ],
        ),
    ],
)
```

### Log output

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ad851f]
    goroutine 15 [running]:
    github.com/hetznercloud/terraform-provider-hcloud/internal/firewall.toHcloudRule({0x1d82e20?, 0xc000a396b0})
    	/home/runner/go/pkg/mod/github.com/hetznercloud/terraform-provider-hcloud@v1.48.1/internal/firewall/resource.go:219 +0x35f
    github.com/hetznercloud/terraform-provider-hcloud/internal/firewall.resourceFirewallCreate({0x28c4ed0, 0xc00016ed20}, 0xc0001d3b80, {0x1ed6d40, 0xc000dc4f00})
    	/home/runner/go/pkg/mod/github.com/hetznercloud/terraform-provider-hcloud@v1.48.1/internal/firewall/resource.go:151 +0x607
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005c9260, {0x28c4e28, 0xc000dd3f50}, 0xc0001d3b80, {0x1ed6d40, 0xc000dc4f00})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/resource.go:778 +0x119
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005c9260, {0x28c4e28, 0xc000dd3f50}, 0x0, 0xc0001d3980, {0x1ed6d40, 0xc000dc4f00})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/resource.go:909 +0xa89
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc000d79da0?, {0xc000149340?, 0xc000ead308?, 0xc000ead4b8?}}, {0x28c4e28, 0xc000dd3f50}, {0x214bd3c, 0xf}, {0x0, 0x0}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.90.0/pkg/tfshim/sdk-v2/provider.go:133 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc000561988, {0x28c4e28?, 0xc000dd3b30?}, 0xc000dd8640)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.90.0/pkg/tfbridge/provider.go:1305 +0x8ae
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create.func1({0x28e13a0?, 0xc000561988?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:375 +0x30
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0xc000e3b080?, 0x203d400, 0xc000ead6c0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:334 +0xb5
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create(0x3a4f630?, {0x28c4e28?, 0xc000dd3b30?}, 0x1cd9ee0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:374 +0x56
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x28c4e28?, 0xc000dd3b30?}, {0x1fd3e80?, 0xc000dd8640?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.130.0/proto/go/provider_grpc.pb.go:651 +0xcb
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x28c4e28, 0xc000dd37d0}, {0x1fd3e80, 0xc000dd8640}, 0xc000ddeb80, 0xc000735938)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3db
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x20e4620, 0xc000e3b080}, {0x28c4e28, 0xc000dd37d0}, 0xc00082ae00, 0xc000848180)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.130.0/proto/go/provider_grpc.pb.go:653 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000946000, {0x28c4e28, 0xc000dd3740}, {0x28d75c0, 0xc000c21500}, 0xc000700000, 0xc000e44120, 0x3a8d5f8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
    google.golang.org/grpc.(*Server).handleStream(0xc000946000, {0x28d75c0, 0xc000c21500}, 0xc000700000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 31
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

### Affected Resource(s)

`hcloud:index:Firewall`

### Output of `pulumi about`

```
warning: using pulumi-language-python from $PATH at /nix/store/44j6rslal79qgks848xb22iv20i0y57l-pulumi-language-python-3.99.0/bin/pulumi-language-python
CLI          
Version      3.99.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
NAME    VERSION
hcloud  1.20.1
python  unknown

Host     
OS       nixos
Version  24.05 (Uakari)
Arch     x86_64

This project is written in python: executable='/home/ben/code/pulumi/hetzner/venv/bin/python3' version='3.11.9'

Current Stack: bmillwood/hetzner/dev

TYPE                     URN
pulumi:pulumi:Stack      urn:pulumi:dev::hetzner::pulumi:pulumi:Stack::hetzner-dev
pulumi:providers:hcloud  urn:pulumi:dev::hetzner::pulumi:providers:hcloud::default_1_20_1


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/bmillwood
User           bmillwood
Organizations  bmillwood
Token type     personal

Dependencies:
NAME           VERSION
pip            24.2.0
pulumi_hcloud  1.20.1
setuptools     75.0.0
wheel          0.44.0

Pulumi locates its logs in /tmp by default
```

### Additional context

(none)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @bmillwood. Thanks for opening an issue. Panicing is never the intended behavior. I have successfully reproduced the issue on my computed. We will take a look soon.

---

Reproducing the problematic configuration on the upstream provider does not panic, indicating a bug in the bridge.

```hcl
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
}

resource "hcloud_firewall" "example" {
  name = "example"
  rule {
    direction   = "in"
    protocol    = "tcp"
    description = "ssh"
    port        = "22"
    source_ips = [
      "::"
    ]
  }
}
```

**Comment by iwahbe** [comment]
Hi @bmillwood. We believe that we have fixed the problem upstream and we are releasing the next provider version [now](https://github.com/pulumi/pulumi-hcloud/actions/runs/10959880135). You shouldn't see the segfault in v1.20.2.
