### ISSUE TITLE
Unable to import an existing server

### ISSUE THREAD

**Issue by vincentbernat** [pulumi/pulumi-hcloud#93]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`pulumi import` fails when importing an existing server when the image used to create it is now unavailable.

### Steps to reproduce

```
 08:40 ❱ pulumi import hcloud:index/server:Server web04.luffy.cx 1413514
Previewing import (dev):
     Type                    Name              Plan       Info
     pulumi:pulumi:Stack     pulumi-take1-dev             1 error
 =   └─ hcloud:index:Server  web04.luffy.cx    import     2 errors

Diagnostics:
  pulumi:pulumi:Stack (pulumi-take1-dev):
    error: preview failed

  hcloud:index:Server (web04.luffy.cx):
    error: hcloud:index/server:Server resource 'web04.luffy.cx' has a problem: Missing required argument: The argument "image" is required, but no definition was found.. Examine values at 'Server.Image'.
    error: Preview failed: one or more inputs failed to validate
```

Expected: Server should be imported
Actual: Error when importing

**Comment by leezen** [comment]
Thanks for reporting and filing the related upstream issue.

**Comment by stack72** [comment]
Closing this out as we've since upgraded to the new version of the provider that implements this fix
